apiVersion: apps/v1
kind: Deployment 
metadata:
  name: user 
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    environment: dev
    tier: database
    code: user-roboshop-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      code: user-roboshop-dev
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        environment: dev
        tier: database
        code: user-roboshop-dev
    spec:
      containers:
      - name: user-pod
        image: "{{ .Values.deployment.image_url }}:{{ .Values.deployment.image_version }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: user-configmap